print("Twinkle, Twinkle, Little Star,")
print("\t How I wonder what you are")
print("\t \t Up above the world so high")
print("\t \t \t Like a diamond in the sky")
print("Twinkle, Twinkle, Little star")
